[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.28"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/dpb587/metalink"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
