[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "2.0.6"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/dpb587/metalink"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
